package:
  name: py3-tensorflow-estimator
  version: 2.15.0
  epoch: 0
  description: TensorFlow's Visualization Toolkit.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - python-3.10
      - py3.10-six

environment:
  contents:
    packages:
      - bash
      - bazel-6
      - build-base
      - busybox
      - ca-certificates-bundle
      - giflib-dev
      - icu-libs
      - libjpeg-turbo-dev
      - openjdk-11
      - patch
      - python-3.10
      - py3.10-pip
      - py3.10-tensorflow-core
      - py3.10-setuptools
  environment:
    JAVA_HOME: /usr/lib/jvm/java-11-openjdk
    BAZEL_CXXOPTS: -std=c++17:-w

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tensorflow/estimator
      tag: v${{package.version}}
      expected-commit: b5f91f8e4113396f0a5f090d6a52d676271caf48

  - runs: |
      bazel build //tensorflow_estimator/tools/pip_package:build_pip_package
      bazel-bin/tensorflow_estimator/tools/pip_package/build_pip_package /tmp/estimator_pip
      python3.10 -m pip install --verbose \
        --no-index --no-build-isolation --no-deps \
        --force-reinstall --no-compile --prefix=/usr "--root=${{targets.contextdir}}" /tmp/estimator_pip/tensorflow_estimator-2.15.0-py2.py3-none-any.whl

test:
  environment:
    contents:
      packages:
        - python-3.10
        - py3.10-pip
  pipeline:
    - runs: |
        pip install tensorflow==${{package.version}}
        pip uninstall -y tensorflow-estimator
        python -c "import tensorflow as tf; print(tf.__version__); print(tf.estimator.__version__)"

update:
  enabled: true
  github:
    identifier: tensorflow/tensorboard
    use-tag: true
    strip-prefix: v
