package:
  name: py3-tensorboard
  version: 2.15.0
  epoch: 0
  description: TensorFlow's Visualization Toolkit.
  copyright:
    - license: Apache-2.0
  resources:
    cpu: 14
    memory: 50Gi
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - bash
      - bazel-6
      - build-base
      - busybox
      - ca-certificates-bundle
      - openjdk-11
      - patch
      - py3-absl-py
      - py3-numpy
      - py3-pip
      - py3-protobuf
      - py3-setuptools
      - python3-dev
  environment:
    JAVA_HOME: /usr/lib/jvm/java-11-openjdk
    BAZEL_CXXOPTS: -std=c++17:-w

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tensorflow/tensorboard
      tag: ${{package.version}}
      expected-commit: 8c1293477b31a32438a20ada2d2e479267057fdc

  - runs: |
      bazel build tensorboard:tensorboard
      ./bazel-bin/tensorboard/tensorboard
      mkdir -p "${{targets.contextdir}}/usr/bin"

update:
  enabled: true
  github:
    identifier: tensorflow/tensorboard
    use-tag: true
    strip-prefix: v
