package:
  name: py3-tensorboard
  version: 2.15.0
  epoch: 0
  description: TensorFlow's Visualization Toolkit.
  copyright:
    - license: Apache-2.0
  resources:
    cpu: 14
    memory: 50Gi
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - apk-tools # testing
      - bash
      - bazel-6
      - build-base
      - busybox
      - ca-certificates-bundle
      - openjdk-11
      - patch
        #- py3.10-numpy
      - py3.10-pip
        #- py3.10-protobuf
        #      - py3.10-requests
      - py3.10-tensorflow-core
      - python-3.10
      - tensorflow-core
  environment:
    JAVA_HOME: /usr/lib/jvm/java-11-openjdk
    BAZEL_CXXOPTS: -std=c++17:-w

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tensorflow/tensorboard
      tag: ${{package.version}}
      expected-commit: 553dedcaf713206457e437c07a09da971048f945

  - name: "Install dependencies"
    runs: |
      # Recommendation is to use the host pip instead of using venv.
      # Pip will complain about being run as root - this disables that warning.
      export PIP_ROOT_USER_ACTION=ignore
      # Install to target dir.
      # Ignore installed packages, since this looks at the builder host packages, when we're trying to install
      # the necessary packages into the target directory.
      python3.10 -m pip install --ignore-installed --prefix=/usr absl-py
      python3.10 -m pip install --ignore-installed --prefix=/usr setuptools
      python3.10 -m pip install --ignore-installed --prefix=/usr six
      python3.10 -m pip install --ignore-installed --prefix=/usr werkzeug
      python3.10 -m pip install --ignore-installed --prefix=/usr grpcio
      python3.10 -m pip install --ignore-installed --prefix=/usr google-auth-oauthlib
      python3.10 -m pip install --ignore-installed --prefix=/usr numpy==1.26.4
      python3.10 -m pip install --ignore-installed --prefix=/usr protobuf
      python3.10 -m pip install --ignore-installed --prefix=/usr requests

  - runs: |
      bazel build tensorboard:tensorboard
      ./bazel-bin/tensorboard/tensorboard
      mkdir -p "${{targets.contextdir}}/usr/bin"

update:
  enabled: true
  github:
    identifier: tensorflow/tensorboard
    use-tag: true
    strip-prefix: v
